#!/bin/sh

# need at least 2 stats to get accurate result
iostat -t proc -c 2 | sed -ne '$p' | {
    read ttyin ttyout user nice sys intr idle left
    if [ "$BLOCK_BUTTON" = 1 ]; then
        echo "CPU: user=$user% nice=$nice% sys=$sys% intr=$intr% idle=$idle%"
    else
        printf "%-4s\n" "$((100 - idle))%"
    fi
}
