#!/bin/sh

iostat -t proc | sed -ne '3p' | {
    read ttyin ttyout user nice sys intr idle left
    if [ "$BLOCK_BUTTON" = 1 ]; then
        echo "CPU: user=$user% nice=$nice% sys=$sys% intr=$intr% idle=$idle%"
    else
        echo "$((100 - idle))%"
    fi
}
