#!/bin/sh

humanize() {
    local n=$1

    [ $n -lt 1024 ] && { RESULT="${n}B/s"; return; }

    n=$(( n / 1024 )); [ $n -lt 1024 ] && { RESULT="${n}KB/s"; return; }
    n=$(( n / 1024 )); [ $n -lt 1024 ] && { RESULT="${n}MB/s"; return; }
    n=$(( n / 1024 )); RESULT="${n}GB/s"
}

interface=`netstat -rn4 | grep ^default | head -n 1`
interface=${interface##* }

netstat -I "$interface" -w 1 -q 1 -d | sed -ne '3p' | {
    read ipackets ierrs idrops ibytes opackets oerrs obytes colls odrops left

    humanize $ibytes; rx=$RESULT
    humanize $obytes; tx=$RESULT

    if [ "$BLOCK_BUTTON" = 1 ]; then
        msg="rx=$rx"
        msg="$msg ipkt=$ipackets"
        [ $ierrs = 0 ] || msg="$msg ierr=$ierrs"
        [ $idrops = 0 ] || msg="$msg idrop=$idrops"

        msg="$msg tx=$tx"
        msg="$msg opkt=$opackets"
        [ $oerrs = 0 ] || msg="$msg oerr=$oerrs"
        [ $odrops = 0 ] || msg="$msg odrop=$odrops"
        [ $colls = 0 ] || msg="$msg coll=$colls"

        echo "Net $interface: $msg"
    else
        printf "$interface  %-7s  %-7s\n" $rx $tx
    fi
}
